#!/usr/bin/env python

# file: /data/courses/ece_1111/current/labs/lab_03/p04/ortiz_damien
#Verion: 6.0

#--------------------------------------------------------------------------

#Python program will add any matrices contained within files

#--------------------------------------------------------------------------

#Imports

#--------------------------------------------------------------------------

#Allows us to get system infomation such as command line arguments
#
import sys

#Allows us to revieve OS information
#
import os

#--------------------------------------------------------------------------

#Function Code

#--------------------------------------------------------------------------

#Function will add the matrices entered as lists of lists
#
def matrixToElements(numList1, numList2):
        
        #Creates blank output to be filled
        #
        x = 0
        y = 0
        output = []
        finalOut = []
        #Logic will check if the matrices are of the same size
        #
        if len(numList1) != len(numList2) or len(numList1[0]) != len(numList2[0]):


                #if they are not the same size we make our output "break"
                #
                output = "break"
        else:
                
                #If they are the same size we compute their addition
                #
                
                #The nested loops are used to get the individual elements of each matrix
                # 
                for i in range(len(numList1)):

                        #Creates a list of the rows
                        #
                        matrixList1 = numList1[i]
                        matrixList2 = numList2[i]

                        #Creates blank rows to be added to matrix
                        #
                        rows = []
                        for j in range(len(matrixList1)):

                                #Create lists of the rows of each matrix
                                #
                                rowList1 = matrixList1[j]
                                rowList2 = matrixList2[j]
                                #Creates blank elements to be added to rows
                                #
                                element = []
                                #Checks to see if the file contains only numbers
                                #
                                if (type(rowList1) == str):
                                        
                                        #Creates individual elements then adds them and places it in the result matrix
                                        #                                                
                                        if rowList1.isdigit():
                                                x = int(rowList1)
                                        else:
                                                #If the element is a non number replaces it with zero and gives warnign
                                                #
                                                x = 0
                                                print("Warning non integer replaced with zero")
                                #Checks if the object is an int, if so adds it to the elements
                                #
                                elif (type(rowList1) == int):
                                        x = rowList1
                                #If the object is a list this will enter the list and add the number
                                #
                                else:
                                        for k in range(len(rowList1)):
                                                x = int(rowList1[k])
                                #Checks to see if the file contains only numbers
                                #
                                if (type(rowList2) == str):

                                        #Creates individual elements then adds them and places it in the result matrix
                                        #                                                                 
                                        if rowList2.isdigit():
                                                y = int(rowList2)                                        
                                        else:
                                                #If the element is a non number replaces it with zero and gives warnign
                                                #
                                                y = 0
                                                print("Warning non integer replaced with zero")
                                #Checks if the object is an int, if so adds it to the elements
                                #
                                elif (type(rowList2) == int):
                                        y = rowList2
                                #If the object is a list this will enter the list and add the number
                                #
                                else:
                                        for k in range(len(rowList2)):
                                                y = int(rowList2[k])

                                #Adds (x+y) onto list of elements for this row
                                #
                                addElement = int(x)+int(y)                               
                                element.append(addElement)

                                #Adds the list of elements to the row list
                                #
                                rows.append(element)
                        #Adds the list of rows to the output matrix
                        #
                        output.append(rows)


                        

        #Returns output matrix made from addition
        #
        return output

#main function
#
def main(argv):

        #Sets up variables that will be used to add elements as a placeholder matrix
        #
        x = []
        mat1 = []
        output = []
        #Takes the filenames we input into the command line and stores them
        # in a variable
        #
        file_input = argv[1:]

        #Creates empty name of file to be used in the except
        #
        current_file = ""
               
        #Try and except checks whether the file exists before trying to
        # operate on it
        #
        try:
                #Loop opens each file within our command line
                #
                for i in range(len(file_input)):
                        current_file = file_input[i]
                        #Opens and closes each file even if errors occur
                        #
                        with open(file_input[i], "r") as FILE:

                                #Creates a list of all the lines within the file
                                #
                                lines = FILE.readlines()

                                #Loops through each line within the file
                                #
                                for idx, line in enumerate(lines):
                                        
                                        #gets rid of excess white space
                                        #
                                        listNums = line.strip()

                                        #Turns each character seperated
                                        # by white space into element
                                        #
                                        listNums = listNums.split()
                                        
                                        #Adds the element to x variable
                                        #
                                        x.append(listNums)

                                        #Logic checks if this is the last line within the file
                                        #
                                        if idx == (len(lines)-1):

                                                #Adds the x matrix as one element of the mat1 list of lists
                                                #
                                                mat1.append(x)

                                                #Empty the x variable to use again for the next file
                                                #
                                                x = []
                        #Only on the first file we set output = mat1[0] to be added to other matrices
                        #
                        if i ==0:
                                output = mat1[0]
                        #Loops through each matrix contained within mat1 to add them
                        #
                        for j in range(1, len(mat1)):
                                b = []
                                #Checks for the content of the output in order to be used for an error case
                                #
                                if output == "break":
                                        #Gets out of the for loop to no longer change the output
                                        #
                                        break
                                #If the output is not "break" allows output to be changed
                                #                                
                                #Call our matrixToElements function to add all files listed         
                                #
                                b = matrixToElements(mat1[j], output)
                                output = b
                                if j != 0:
                                        mat1.remove(mat1[j])
                        #Checks whether there should be an output to print yet 
                        #
                        if i != 0:
                                #Checks the output did not come from uncompatible matrices
                                if output != "break":
                                        #Prints the output matrices line by line with a seperator
                                        #        
                                        print("Output %d: " % (i))               
                                        for j in range(len(output)):
                                               print(output[j])
                                        print("-----------------------")

                                                #Creates the error message for when the matrices are incompatible
                                                #
                                elif i != len(file_input):
                                        print("Matrix sizes do not match.")

        #Error case for when the file does not exist
        #
        except FileNotFoundError:

         #Tells the user the file they chose does not exist
         #
         print("The file '%s' does not exist" % current_file)

        # exit gracefully
        #
        return True

# begin gracefully
#
if __name__ == '__main__':
    main(sys.argv[0:])
        
#End of file
